# Values to configure the resources:
# Application CR - kratix dependencies
# Application CR - kratix resources
# Secret         - Gitea server credentials

destination:
  name: worker-1
  path: worker-1

stateStore:
  kind: GitStateStore
  reference: gitea

labels:
  environment: dev
  cluster: worker-1
  team: team-a