#
# vcluster kratix agent configuration based on k8s distro
#
# It includes part of the networking section a replicateService able to
# make the idpbuilder gitea server accessible from a vcluster:
#
# Host kubernetes service: my-gitea-http.gitea is translated into the
# vcluster kubernetes service: virt-gitea-http.virt-gitea-namespace
#
#
controlPlane:
  distro:
    k8s:
      enabled: true
  backingStore:
    etcd:
      deploy:
        enabled: true
  statefulSet:
    scheduling:
      podManagementPolicy: OrderedReady
  # Add an ingress host to access the vcluster Kubernetes API
  ingress:
    enabled: true
    host: worker-1.cnoe.localtest.me
    spec:
      ingressClassName: nginx
networking:
  replicateServices:
    fromHost:
      - from: gitea/my-gitea-http
        to: virt-gitea-namespace/virt-gitea-http
# To customize the content of the vc-<vcluster> secret
exportKubeConfig:
  server: https://worker-1.cnoe.localtest.me:8443
  context: vcluster_worker-1_worker-1_kind-kratix

#
# k get secret/vc-worker-1 -n worker-1 -ojson | jq -r '.data.config' | base64 -d > worker-1-kube.cfg
# k --kubeconfig=worker-1-kube.cfg get pod -A

# Resources to be deployed post vcluster created
# - Argo CD
#
experimental:
  deploy:
    vcluster:
      helm:
        - chart:
            name: argo-cd
            repo: https://argoproj.github.io/argo-helm
            version: v7.7.3 # appVersion: v2.13.4
          release:
            name: argocd
            namespace: argocd
          values: |-
            dex:
              enabled: false
            notifications:
              enabled: false
            applicationSet:
              enabled: false
            ingress:
              enabled: false
            crds:
              install: true
              keep: true

            configs:
              params:
                server.insecure: true