apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix
  namespace: argocd
  labels:
    app.kubernetes.io/name: kratix
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kratix-platform-system
  source:
    repoURL: cnoe://manifests
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true