apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-agents
  namespace: argocd
  labels:
    app.kubernetes.io/name: kratix-agents
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://
    targetRevision: HEAD
    path: vclusters
    helm:
      valuesObject:
        argocd:
          namespace: argocd
          project: default
          destination:
            server: https://kubernetes.default.svc
            namespace:
        vcluster:
          helm:
            repoURL: https://charts.loft.sh
            targetRevision: "0.24.0"
            valuesFileUrl: https://raw.githubusercontent.com/ch007m/my-kratix-idpbuilder/refs/heads/main/idp/kratix-agents/vclusters/files/vcluster-config.yaml
        # vclusters and destinations to be created
        clusters:
          - name: worker-1
            path: worker-1
            organization: team-a
          - name: worker-2
            path: worker-2
            organization: team-b
        destinationResourcesVcluster:
          repoURL: cnoe://
          targetRevision: HEAD
          path: destination-vcluster
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true