apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: trust-manager
spec:
  destination:
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.17.1
      helm:
        valuesObject:
          crds:
            enabled: true
    - chart: trust-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v0.16.0
      helm:
        valuesObject:
          image:
            tag: v0.16.0
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true