controlPlane:
  backingStore:
    etcd:
      deploy:
        enabled: true
  distro:
    k8s:
      enabled: true
  statefulSet:
    scheduling:
      podManagementPolicy: OrderedReady
networking:
  replicateServices:
    fromHost:
      - from: gitea/my-gitea-http
        to: virt-gitea-namespace/virt-gitea-http