controlPlane:
  backingStore:
    etcd:
      deploy:
        enabled: true
  distro:
    k8s:
      enabled: true
  statefulSet:
    scheduling:
      podManagementPolicy: OrderedReady
networking:
  replicateServices:
    fromHost:
      - from: gitea/my-gitea-http
        to: virt-gitea-namespace/virt-gitea-http

experimental:
  deploy:
    vcluster:
      helm:
        - chart:
            name: argo-cd
            repo: https://argoproj.github.io/argo-helm
            version: v7.7.3 # appVersion: v2.13.4
          release:
            name: argocd
            namespace: argocd
          values: |-
              dex:
                enabled: false
              notifications:
                enabled: false
              applicationSet:
                enabled: false
              ingress:
                enabled: false
              crds:
                # -- Install and upgrade CRDs
                install: true
                # -- Keep CRDs on chart uninstall
                keep: true
              
              configs:
                params:
                  server.insecure: true