# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

argocd:
  namespace: argocd
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace:

# vclusters and destinations to be created
clusters:
  - name: worker-1
    path: worker-1
    organization: team-a

vcluster:
  helm:
    repoURL: https://charts.loft.sh
    targetRevision: "0.24.0"
    valuesFileUrl: https://raw.githubusercontent.com/ch007m/my-kratix-idpbuilder/refs/heads/main/helm-kratix-agents/files/vcluster-config.yaml
#####
