apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitea-{{ $.Values.clusterName }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    managed-by: argocd.argoproj.io
stringData:
  type: "git"
  url: "{{ $.Values.giteaServer.url }}/{{ $.Values.gitKratix.org }}/{{ $.Values.gitKratix.repository }}"
  password: "{{ $.Values.giteaServer.password }}"
  username: "{{ $.Values.giteaServer.username }}"
  insecure: "true"