{{- $root := . -}}

{{- /* Loop over the clusters */ -}}
{{- range $cluster := .Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $cluster.name }}
  namespace: argocd
  labels:
    vcluster: {{ $cluster.name }}
    organization: {{ $cluster.organization }}
spec:
  project: {{ $root.Values.argocd.project }}
  sources:
    - chart: vcluster
      repoURL: {{ $root.Values.vcluster.helm.repoURL }}
      targetRevision: {{ $root.Values.vcluster.helm.targetRevision }}
      helm:
        valueFiles:
          - {{ $root.Values.vcluster.helm.valuesFileUrl }}
    - repoURL: {{ $root.Values.destinationResourcesVcluster.repoURL }}
      targetRevision: {{ $root.Values.destinationResourcesVcluster.targetRevision }}
      path: {{ $root.Values.destinationResourcesVcluster.path }}
      helm:
        valuesObject:
          clusterName: {{ $cluster.name }}
          gitKratix:
            org: kratix
            repository: state
          # See destination-vcluster default values file
  destination:
    namespace: {{ $cluster.name }}
    server: {{ $root.Values.argocd.destination.server }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}
