apiVersion: v1
kind: ServiceAccount
metadata:
  name: kratix-job
  namespace: kratix
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kratix-job-role
  namespace: kratix
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kratix-job-role-binding
  namespace: kratix
subjects:
  - kind: ServiceAccount
    name: kratix-job
    namespace: kratix
roleRef:
  kind: Role
  name: kratix-job-role
  apiGroup: rbac.authorization.k8s.io