apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-job
  namespace: kratix
  labels:
    app.kubernetes.io/name: kratix-job
spec:
  destination:
    namespace: kratix
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://jobs
    targetRevision: HEAD
    path: "."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true