apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-new-destination
  namespace: argocd
  labels:
    app.kubernetes.io/name: kratix-new-destination
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
  source:
    repoURL: cnoe://kratix-new-destination
    targetRevision: HEAD
    path: .
    helm:
      valuesObject:
        destination:
          name: worker-1
          path: worker-1

        stateStore:
          kind: GitStateStore
          reference: gitea

        labels:
          environment: dev
          cluster: worker-1
          team: team-a
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
